export const roleAliases = {
  ADMIN: 'HOSPITAL_ADMIN',
  HOSPITAL_MANAGER: 'HOSPITAL_ADMIN',
  BILLING_EXECUTIVE: 'CASHIER',
};

export const normalizeRole = (role) => {
  const normalizedRole = String(role || '').trim().toUpperCase();
  return roleAliases[normalizedRole] || normalizedRole;
};

const commonItems = [
  { label: 'Dashboard', to: 'dashboard' },
  { label: 'Notifications', to: 'notifications' },
  { label: 'Profile', to: 'profile' },
  { label: 'Settings', to: 'settings' },
];

export const roleNavigation = {
  PATIENT: [
    commonItems[0],
    { label: 'My Profile', to: 'profile' },
    { label: 'Appointments', to: 'appointments' },
    { label: 'Medical Record', to: 'medical-record' },
    { label: 'Lab Results', to: 'lab-results' },
    { label: 'Prescriptions', to: 'prescriptions' },
    { label: 'Bills & Payments', to: 'bills' },
    { label: 'Messages', to: 'messages' },
    commonItems[1],
    commonItems[3],
  ],
  RECEPTIONIST: [
    commonItems[0],
    { label: 'Patients', to: 'patients' },
    { label: 'Register Patient', to: 'patients/new' },
    { label: 'Appointments', to: 'appointments' },
    { label: 'Check-in & Queue', to: 'queue' },
    { label: 'Visits', to: 'visits' },
    { label: 'Messages', to: 'messages' },
    commonItems[1],
  ],
  DOCTOR: [
    commonItems[0],
    { label: 'My Profile', to: 'profile' },
    { label: 'Schedule', to: 'schedule' },
    { label: 'Appointments', to: 'appointments' },
    { label: 'Patients', to: 'patients' },
    { label: 'Consultations', to: 'consultations' },
    { label: 'Lab Orders', to: 'lab-orders' },
    { label: 'Radiology Orders', to: 'radiology-orders' },
    { label: 'Follow-ups', to: 'follow-ups' },
    commonItems[1],
    commonItems[3],
  ],
  NURSE: [
    commonItems[0],
    { label: 'My Profile', to: 'profile' },
    { label: 'Assigned Patients', to: 'assigned-patients' },
    { label: 'Vitals', to: 'vitals' },
    { label: 'Nursing Notes', to: 'nursing-notes' },
    { label: 'Medication Administration', to: 'medications' },
    { label: 'Ward', to: 'ward' },
    { label: 'Admissions', to: 'admissions' },
    commonItems[1],
  ],
  LAB_TECHNICIAN: [
    commonItems[0],
    { label: 'Doctor Requests', to: 'orders' },
    { label: 'Sample Collection', to: 'sample-collection' },
    { label: 'Processing', to: 'processing' },
    { label: 'Results', to: 'results' },
    { label: 'Verification', to: 'verification' },
    { label: 'Test Catalog', to: 'tests' },
    { label: 'Profile', to: 'profile' },
    commonItems[1],
  ],
  RADIOLOGY_TECHNICIAN: [
    commonItems[0],
    { label: 'Requests', to: 'requests' },
    { label: 'Processing', to: 'processing' },
    { label: 'Reports', to: 'reports' },
    { label: 'Completed', to: 'completed' },
    { label: 'Profile', to: 'profile' },
    commonItems[1],
  ],
  PHARMACIST: [
    commonItems[0],
    { label: 'Prescription Requests', to: 'prescriptions' },
    { label: 'Dispensing', to: 'dispensing' },
    { label: 'Medicines', to: 'medicines' },
    { label: 'Inventory', to: 'inventory' },
    { label: 'Low Stock', to: 'low-stock' },
    { label: 'Expiry', to: 'expiry' },
    { label: 'Profile', to: 'profile' },
    commonItems[1],
  ],
  CASHIER: [
    commonItems[0],
    { label: 'Invoices', to: 'invoices' },
    { label: 'Payments', to: 'payments' },
    { label: 'Receipts', to: 'receipts' },
    { label: 'Outstanding', to: 'outstanding' },
    { label: 'Daily Collection', to: 'daily-collection' },
    { label: 'Profile', to: 'profile' },
    commonItems[1],
  ],
  HOSPITAL_ADMIN: [
    commonItems[0],
    { label: 'Users', to: 'users' },
    { label: 'Staff', to: 'staff' },
    { label: 'Patients', to: 'patients' },
    { label: 'Appointments', to: 'appointments' },
    { label: 'Departments', to: 'departments' },
    { label: 'Wards & Beds', to: 'wards' },
    { label: 'Inventory', to: 'inventory' },
    { label: 'Billing', to: 'billing' },
    { label: 'Audit Logs', to: 'audit-logs' },
    commonItems[1],
    commonItems[3],
  ],
  SUPER_ADMIN: [
    commonItems[0],
    { label: 'Hospitals', to: 'hospitals' },
    { label: 'Users', to: 'users' },
    { label: 'Roles & Permissions', to: 'roles' },
    { label: 'System Health', to: 'system-health' },
    { label: 'Security', to: 'security' },
    { label: 'Audit Logs', to: 'audit-logs' },
    { label: 'Reports', to: 'reports' },
    { label: 'Profile', to: 'profile' },
    commonItems[3],
  ],
};

export const roleTitles = {
  PATIENT: 'Patient portal',
  RECEPTIONIST: 'Front desk',
  DOCTOR: 'Clinical workspace',
  NURSE: 'Nursing station',
  LAB_TECHNICIAN: 'Laboratory',
  RADIOLOGY_TECHNICIAN: 'Radiology',
  PHARMACIST: 'Pharmacy',
  CASHIER: 'Finance desk',
  HOSPITAL_ADMIN: 'Hospital administration',
  SUPER_ADMIN: 'Platform administration',
};
